#!/bin/sh
DIR="$(readlink -f "${0}")"
DIR="$(dirname "${DIR}")"

if [ $# -lt 3 ]; then
	echo 'usage: ffi-cdecl arm-none-linux-gnueabi-gcc file.c output_file.lua'
	exit 1
fi

TOOL="${1}"
INPUT="${2}"
OUTPUT="${3}"

"${TOOL}" -S "${INPUT}" ${CPPFLAGS} -I"${DIR}/gcc-lua-cdecl/ffi-cdecl" -fplugin="${DIR}/gcc-lua/gcc/gcclua.so" -fplugin-arg-gcclua-script="${DIR}/ffi-cdecl.lua" -fplugin-arg-gcclua-output="${OUTPUT}"
