name: Build Docker image on PR

on:
  pull_request:
    paths:
      - 'nightswatcher/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nightswatcher
          push: false
          tags: your-image-name:pr-${{ github.event.pull_request.number }}
